customhost = "emp-database.cntdwxoqg2np.us-east-1.rds.amazonaws.com"
customuser = "admin"
custompass = "admin123"
customdb = "employee"
custombucket = "ongzhenchun-empsbucket"
customregion = "us-east-1"