customhost = "ems-database.c9bsyiia4gxk.us-east-1.rds.amazonaws.com"
customuser = "admin"
custompass = "admin123"
customdb = "employee"
custombucket = "emp-image-ongzhenchun"
customregion = "us-east-1"